### PR TITLE
Suggestion: Use nix dockerTools to build the image

### PR DESCRIPTION
**Pull request by rvl**
Hi, have you considered using [pkgs.dockerTools.buildImage](https://nixos.org/nixpkgs/manual/#sec-pkgs-dockerTools)?

It should make rebuilds quicker when adding and removing packages.

It won't make the image much smaller -- I think (but haven't confirmed) it's because the nix haskell infrastructure doesn't yet support "multiple output" derivations yet (i.e. docs, libraries, binaries in separate packages).

Please regard this pull request as just a suggestion.

Cheers

### CODE REVIEW

**Comment by jwiegley** [comment]
Thanks!  This at least dropped the image down to a single layer of 3.612 (~400 MB savings).  However, in the `docker images` list, it says it was created 46 years ago, so some metadata is not being set.

But the best thing is that I can truly add new packages incrementally now, paying only the cost of building the new package and re-combining the hoogle databases.  I do have to re-upload the whole 3.6 GB though.

Any thoughts on how to bring the image size down?  Maybe I should sweep through `/nix/store` at the end and just force-delete all the non-documentation files?

**Comment by rvl** [comment]
No prob, I really like what Lethalman has created here.

I think the 400MB saving comes from not having any base image. If you need to poke around inside the image, add `pkgs.bashInteractive` to the `contents` list.

Force-deleting non-documentation sounds like a good way to trim the image. This could be done from the `runAsRoot` script. But at the moment I can't think of a good way to exempt the dynamically linked hoogle executable and its libraries from the purge.

The timestamp of 46 years ago is hard-coded into the nix dockerTools. Basically, a date must be chosen so that the nix build is deterministic. Arguably, the timestamp could be the most recent timestamp of all derivations which contributed to the image, or it could be configured by the caller of the `dockerTools.buildImage` function. Either way, this would require a PR on nixpkgs.

For now, this is a possible workaround -- it seds the json metadata file.

    nix-build | xargs gzip -dc | sed '0,/1970-01-01T00:00:01Z/s//2016-09-11T20:30:27Z/' | docker load

**Comment by jwiegley** [comment]
@rvl Do you know how to get the built image to garbage collect away build dependencies, like `gcc`?  They are bloating the final image unnecessarily.

**Comment by rvl** [comment]
At the moment it's not possible. The contents of the docker image are already a "minimal" closure. I think nix `haskellPackages` needs to support splitting into multiple outputs. Then the hypothetical future `package.doc` outputs wouldn't depend on `gcc`.

For the time being, do you think it's possible to statically link hoogle (I am guessing we need to override and set `enableSharedExecutables = false;`)? Copy hoogle to `/bin`, then use the tactical nuclear option of deleting everything which isn't html or a hoogle index. (I can't experiment right now but would need to check whether the resulting hoogle executable still needs `libc.so`, etc.)

**Pull request merged**
